import Link from "next/link";
import type { Perfume } from "@/lib/types";
import { formattedReferencePrice, publicText } from "@/lib/catalogDisplay";
import { ProductImage } from "@/components/perfume/ProductImage";

export function HomeCatalogPreview({ perfumes, familias }: { perfumes: Perfume[]; familias: string[] }) {
  const items = perfumes.slice(0, 5); if (!items.length) return null;
  return <section className="bg-[#faf6ee] py-16 dark:bg-[#100d0a] lg:py-20"><div className="mx-auto w-full max-w-[1440px] px-6 lg:px-10 xl:px-14">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-5 border-b border-line pb-4"><div><p className="font-plex text-[10px] uppercase tracking-[.2em] text-ink">Catálogo seleccionado</p><p className="mt-2 max-w-[54ch] font-sans text-xs leading-5 text-muted">Producto visual desde Amazon; lectura editorial y datos olfativos desde Aromia.</p></div><Link href="/catalogo" className="nav-link font-sans text-xs text-muted transition hover:text-gold-contrast">Ver catálogo completo →</Link></div>
    <form action="/catalogo" className="mb-8 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-[1.25fr_1fr_1fr_1fr_auto]"><label className="sr-only" htmlFor="home-familia">Familia olfativa</label><select id="home-familia" name="familia" defaultValue="" className="min-h-12 border border-line bg-[#fffdf8] px-4 font-sans text-xs text-ink outline-none dark:bg-[#17120d]"><option value="">Todas las familias</option>{familias.slice(0,18).map(f=><option key={f} value={f}>{f}</option>)}</select><select name="genero" defaultValue="" aria-label="Género" className="min-h-12 border border-line bg-[#fffdf8] px-4 font-sans text-xs text-ink dark:bg-[#17120d]"><option value="">Todos los géneros</option><option value="masculino">Masculino</option><option value="femenino">Femenino</option><option value="unisex">Unisex</option></select><select name="categoria" defaultValue="" aria-label="Categoría de precio" className="min-h-12 border border-line bg-[#fffdf8] px-4 font-sans text-xs text-ink dark:bg-[#17120d]"><option value="">Todos los precios</option><option value="económico">Económico</option><option value="medio">Medio</option><option value="premium">Premium</option><option value="lujo">Lujo</option></select><select name="orden" defaultValue="" aria-label="Ordenar" className="min-h-12 border border-line bg-[#fffdf8] px-4 font-sans text-xs text-ink dark:bg-[#17120d]"><option value="">Orden editorial</option><option value="rating">Mejor valorados</option><option value="precio_asc">Precio menor</option><option value="precio_desc">Precio mayor</option></select><button type="submit" className="min-h-12 bg-gold-contrast px-6 font-plex text-[9px] uppercase tracking-[.15em] text-white">Aplicar filtros</button></form>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-5">{items.map(perfume=>{const family=publicText(perfume.familia_olfativa);const price=formattedReferencePrice(perfume);const buyHref=`/api/catalog-buy/${encodeURIComponent(perfume.slug)}`;return <article key={perfume.slug} className="group overflow-hidden border border-line bg-[#fffdf9] transition duration-300 hover:-translate-y-1 hover:border-gold hover:shadow-lux dark:bg-[#15110d]"><a href={buyHref} target="_blank" rel="sponsored noopener noreferrer" aria-label={`Ver ${perfume.nombre} en Amazon`} className="relative block aspect-[4/5] overflow-hidden bg-[#fbfaf7] dark:bg-[#f7f4ee]"><ProductImage slug={perfume.slug} alt={`${perfume.nombre} de ${perfume.marca}`} mode="card"/><span className="absolute right-3 top-3 z-[2] border border-line bg-[#fffdf9]/90 px-2 py-1 font-plex text-[7px] uppercase tracking-[.14em] text-muted backdrop-blur">Amazon ↗</span></a><Link href={`/catalogo/${perfume.slug}`} className="block p-4"><p className="truncate font-display text-lg leading-tight text-ink">{perfume.nombre}</p><p className="mt-1 truncate font-sans text-[11px] text-muted">{perfume.marca}</p>{family?<p className="mt-2 truncate font-plex text-[8px] uppercase tracking-[.1em] text-gold-contrast">{family}</p>:null}<p className="mt-4 font-display text-lg text-ink">{price??"Ver disponibilidad"}</p>{perfume.rating_promedio?<div className="mt-2 flex items-center gap-2"><span className="text-[10px] tracking-[.08em] text-gold">★★★★★</span><span className="font-plex text-[8px] text-muted">{perfume.rating_promedio.toFixed(1)}</span></div>:null}</Link></article>})}</div>
  </div></section>;
}
