import { notFound } from "next/navigation";
import Link from "next/link";
import "../editorial-v1.css";
import "./story.css";

const data:Record<string,{territory:string,title:string,deck:string,kind:string,sections:{h:string,p:string}[]}>={
"el-ambar-que-nunca-toco-una-ballena":{territory:"Materia",kind:"ambroxan",title:"El ámbar que nunca tocó una ballena",deck:"Casi cualquier perfume ambarado de las últimas décadas conoce esta molécula. Su historia, sin embargo, empieza mucho antes de que tuviera nombre.",sections:[{h:"El problema tenía forma de ballena",p:"Durante siglos, el ámbar gris fue una rareza marina: escaso, imprevisible y ligado al cachalote. La perfumería necesitaba otra manera de llegar a ese efecto."},{h:"Una hoja de salvia, no un océano",p:"El giro llegó desde la salvia esclarea. Del sclareol surgió una ruta hacia materiales ambarados modernos: la historia dejó de depender de encontrar algo flotando en el mar."},{h:"1946 → 1950 → 1977",p:"Aislamiento, síntesis y confirmación fueron convirtiendo una rareza natural en conocimiento reproducible."},{h:"Cuando alguien decide mostrar la molécula sola",p:"Décadas después, Molecule 02 haría algo extraño: convertir el ambroxan, normalmente parte de una fórmula, en la idea central del perfume."}]},
"el-perfumista-que-no-teme-exagerar":{territory:"Personas",kind:"ropion",title:"El perfumista que no teme exagerar",deck:"Dominique Ropion trabaja como si la moderación fuera una decisión que primero hay que justificar.",sections:[{h:"Formado para medir",p:"La técnica está antes que el gesto. Su formación y décadas de fórmulas explican por qué el exceso puede seguir sintiéndose preciso."},{h:"La técnica tiene nombre: sobredosis",p:"En algunas composiciones, una materia deja de ser un detalle y altera la escala entera del perfume. La rosa puede ocupar demasiado espacio a propósito."},{h:"Lo que decidió no usar",p:"La abundancia también se entiende por ausencia. En Portrait of a Lady, ciertas herramientas familiares de la perfumería moderna no fueron la respuesta."},{h:"Sí, pero",p:"Exagerar no significa añadirlo todo. A veces significa elegir qué merece ser llevado hasta un extremo y qué debe desaparecer."}]},
"el-perfume-que-encargo-un-sultan":{territory:"Fuera del radar · Historias",kind:"amouage",title:"El perfume que encargó un sultán",deck:"En 1982, Guy Robert viajó a Mascate para responder a un encargo poco habitual: crear un perfume capaz de hablar desde Omán al mundo.",sections:[{h:"Un país que vende incienso desde hace milenios",p:"Antes de Amouage estaba el territorio: resinas, rutas y una relación histórica con el incienso que no necesitaba ser inventada por una marca."},{h:"Un perfumista francés llega a Mascate",p:"Guy Robert llevó consigo otra tradición. El interés de la historia está en el encuentro, no en disfrazar una cultura con la estética de otra."},{h:"La densidad como ambición",p:"Gold se convirtió en el resultado inaugural de esa comisión. Su reputación de fórmula extraordinariamente compleja forma parte de la leyenda de la casa."},{h:"¿El perfume más caro del mundo?",p:"La frase se ha repetido durante años. Repetición no equivale a prueba: Aromia la conserva como reputación, no como dato cerrado."}]}}

export default function Story({params}:{params:{slug:string}}){const s=data[params.slug];if(!s)notFound();return <main className={`ev1 story-page ${s.kind}`}><header className="ev1-nav"><Link href="/editorial-v1" className="ev1-brand">AROMIA</Link><nav><Link href="/editorial-v1">Portada</Link><span>{s.territory}</span></nav><Link href="/buscar">⌕</Link></header><article><header className="story-hero"><div><p className="ev1-kicker">{s.territory}</p><h1>{s.title}</h1><p className="story-deck">{s.deck}</p></div><div className="story-visual" aria-label="Área visual interpretativa; no representa evidencia documental"/></header>{s.sections.map((x,i)=><section className={`story-section section-${i+1}`} key={x.h}><p className="section-number">0{i+1}</p><div><h2>{x.h}</h2><p>{x.p}</p></div>{i===1&&<div className="story-interruption" aria-hidden="true"/>}</section>)}<aside className="story-close"><p className="ev1-kicker">Seguir explorando</p><p>El perfume puede ser el final de una compra. Aquí preferimos que sea el principio de otra pregunta.</p><Link href="/editorial-v1" className="ev1-read">Volver a la portada →</Link></aside></article></main>}
